import type { Metadata } from "next";
import { Play } from "next/font/google";
import "./globals.css";

import { i18nConfig } from "@/i18nConfig";
import { dir } from "i18next";
import { notFound } from "next/navigation";
import TranslationsProvider from "./TranslationsProvider";
import initTranslations from "../i18n";
import { ReactNode } from "react";

const play = Play({ subsets: ['latin'], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale }
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  if (!i18nConfig.locales.includes(locale)) {
    notFound();
  }

  const namespaces = ["common"];
  const { resources } = await initTranslations(locale, namespaces);

  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={play.className}>
        <TranslationsProvider locale={locale} namespaces={namespaces} resources={resources}>
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
